export const GENRE_OPTIONS = [
  'Portrait',
  'Figure Study',
  'Landscape',
  'Concept Art',
  'Still Life',
  'Abstract',
  'Botanical',
  'Surrealism',
  'Expressionism',
  'Abstract Expressionism',
  'Impressionism',
  'Post-Impressionism',
  'Fauvism',
  'Character Design',
  'Interior Scene',
  'Genre Scene (Everyday Life)',
  'Pattern/Decorative',
  'Other',
];

export const SUBSTRATE_OPTIONS = [
  'Canvas',
  'Canvas Board',
  'Wood Panel',
  'Masonite',
  'Bristol Board',
  'Illustration Board',
  'Watercolor Paper (Hot Press)',
  'Watercolor Paper (Cold Press)',
  'Mixed Media Paper',
  'Sketch Paper',
  'Toned Paper',
  'Vellum',
  'Ramboard',
  'Chipboard',
  'Fabric/Canvas Cloth',
  'Linen',
  'Paper (General)',
  'Cardstock',
  'Clay/Sculptural Surface',
  'Wall/Mural Surface',
  'Digital Canvas',
  'Other',
];

export const MEDIUM_OPTIONS = [
  'Oil',
  'Acrylic',
  'Watercolor',
  'Gouache',
  'Tempera',
  'Ink',
  'Pen and Ink',
  'Graphite/Pencil',
  'Charcoal',
  'Colored Pencil',
  'Pastel (Soft)',
  'Pastel (Oil)',
  'Pastel Pencil',
  'Marker',
  'Airbrush',
  'Spray Paint',
  'Printmaking',
  'Collage/Mixed Media',
  'Gouache and Watercolor',
  'Digital',
  '3D/Sculpture',
  'Other',
];