export const GENRE_OPTIONS = [
  'portrait',
  'self-portrait',
  'figure study',
  'landscape',
  'seascape',
  'cityscape',
  'still life',
  'abstract',
  'surrealism',
  'animal',
  'wildlife',
  'botanical',
  'fantasy',
  'sci-fi',
  'character design',
  'concept art',
  'anime/manga style',
  'caricature',
  'architecture',
  'interior scene',
  'nude/figure',
  'historical',
  'mythological',
  'religious',
  'genre scene (everyday life)',
  'pattern/decorative',
  'typography/lettering',
  'comic/sequential art',
  'other',
];

export const SUBSTRATE_OPTIONS = [
  'canvas',
  'stretched canvas',
  'canvas board',
  'wood panel',
  'birch panel',
  'masonite',
  'bristol board',
  'illustration board',
  'watercolor paper (hot press)',
  'watercolor paper (cold press)',
  'mixed media paper',
  'sketch paper',
  'toned paper',
  'vellum',
  'ramboard',
  'chipboard',
  'fabric/canvas cloth',
  'linen',
  'paper (general)',
  'cardstock',
  'clay/sculptural surface',
  'wall/mural surface',
  'digital canvas',
  'other',
];

export const MEDIUM_OPTIONS = [
  'oil',
  'acrylic',
  'watercolor',
  'gouache',
  'tempera',
  'ink',
  'pen and ink',
  'graphite/pencil',
  'charcoal',
  'colored pencil',
  'pastel (soft)',
  'pastel (oil)',
  'marker',
  'airbrush',
  'spray paint',
  'printmaking',
  'collage/mixed media',
  'encaustic',
  'gouache and watercolor',
  'digital',
  'digital (procreate)',
  'digital (photoshop)',
  'digital (clip studio paint)',
  '3D/sculpture',
  'other',
];
